# Generated by Django 2.1.15 on 2020-08-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=300)),
                ('url', models.TextField(blank=True, max_length=500, null=True)),
                ('comment', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_review_at', models.DateField(null=True)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
