# Generated by Django 2.2.1 on 2019-08-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaced_repetition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_review_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
